name: CI

on:
  schedule:
    - cron:  '0 4 * * 6'

env:
  CI_MAKE: make -f .travis.mk

jobs:
  # https://github.com/marketplace/actions/skip-duplicate-actions#concurrent_skipping
  pre_job:
    continue-on-error: true
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # avoid of duplicating runs on "push & pull_request"
          # avoid of running previous of the updated jobs
          concurrent_skipping: 'same_content'

  coverity:
    needs: pre_job
    if: |
      needs.pre_job.outputs.should_skip != 'true' ||
      github.event_name == 'push'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    # Image built by .gitlab.mk instructions and targets from .travis.mk.
    # Also additional installation of coverity tool installation check
    # exists in target deps_coverity_debian at .travis.mk file.
    container: docker.io/tarantool/testing:debian-buster

    steps:
      - uses: actions/checkout@v1
      - name: test
        run: ${CI_MAKE} test_coverity_debian_no_deps
        env:
          COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: debug
          retention-days: 1000000
          path: test/var/artifacts
