name: CI

on: [push, pull_request]

env:
  CI_MAKE: make -f .travis.mk

jobs:
  osx_10_15:
    runs-on: macos-10.15

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: test
        run: ${CI_MAKE} test_osx_github_actions
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: osx_10_15
          retention-days: 1000000
          path: test/var/artifacts
